#if !canImport(ObjectiveC)
import XCTest

#if swift(>=5.9) && canImport(ContextsMacroPlugin)
extension ContextKeyMacroTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContextKeyMacroTests = [
        ("testNonOptionalPropertyExpansion", testNonOptionalPropertyExpansion),
        ("testOptionalPropertyExpansion", testOptionalPropertyExpansion),
    ]
}
#endif

extension ContextsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContextsTests = [
        ("testContextCreation", testContextCreation),
        ("testContextInput", testContextInput),
        ("testContextInputReset", testContextInputReset),
        ("testContextInputTransform", testContextInputTransform),
        ("testContextInputTransformAndUpdate", testContextInputTransformAndUpdate),
        ("testContextResetAndInputReset", testContextResetAndInputReset),
        ("testContextReset", testContextReset),
        ("testContextUpdate", testContextUpdate),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
#if swift(>=5.9) && canImport(ContextsMacroPlugin)
    return [
        testCase(ContextKeyMacroTests.__allTests__ContextKeyMacroTests),
        testCase(ContextsTests.__allTests__ContextsTests),
    ]
#else
    return [
        testCase(ContextsTests.__allTests__ContextsTests),
    ]
#endif
}
#endif
